#!/usr/bin/env python
from configparser import ConfigParser
import subprocess
import argparse


def main() -> None:
    config = ConfigParser(allow_no_value=False, empty_lines_in_values=False)
    config.optionxform = lambda option: option
    config.read(['/etc/timeline.conf', '~/.config/timeline.conf'])
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'file', nargs='?', default=config.get('timeline', 'MainFile',
                                              fallback='timeline.tln')
    )
    args = parser.parse_args()
    subprocess.run(f'nvim -u TIMELINE_INSTALL_DIR/lib/timeline/nvim.config {args.file}', shell=True)


if __name__ == '__main__':
    main()

